### ISSUE TITLE
Thanks for your plugins

### ISSUE THREAD

**Issue by markgif** [jason-fox/fox.jason.passthrough.pandoc#1]
Hey Jason, this is not an "issue" but a compliment. You've added several cool plugins (such as this pandoc one) to the registry and I wanted to say thanks a lot and keep up the good work!

Regards,
Mark Giffin
https://github.com/markgif

**Comment by lief-erickson** [comment]
@markgif I agree Jason has added some cool looking plugins. Have you tried this one? Have you gotten it to work? I'm trying the test files and I'm not getting the expected output. Are you?

**Comment by markgif** [comment]
Hi @lief-erickson ! No I have not tried it yet. If I had something I needed it for at the moment, I would definitely try it. At a minimum I'd get ideas from it.

**Comment by jason-fox** [comment]
@markgif - I'm glad you like them, an intermediate update to the registry is still pending: https://github.com/dita-ot/registry/pull/59 so at the moment it is always better to follow the instructions on each `README` to down load latest fixes.

The Windows processing issue is now fixed: https://github.com/jason-fox/fox.jason.passthrough/issues/1 - I'll need to make another round of releases.

If you're interested in more details about how all these plug-ins work, I'll be speaking at [DITA-OT Day](https://www.oxygenxml.com/events/2019/dita-ot_day.html#agenda) in Brussels on 9th November 2019. I expect that I'll have the latest round of bug fixes in the registry by then.
