### ISSUE TITLE
Notes are not rendered as <note>.

### ISSUE THREAD

**Issue by jason-fox** [jason-fox/fox.jason.passthrough.pandoc#4]
Related: https://github.com/jason-fox/fox.jason.passthrough/issues/1

Improve Note processing or at least render within `<draft-comment>` or raise a warning at compile time.

**Comment by jason-fox** [comment]
@lief-erickson

I've added basic `<note>` support, could you check if it works for you on your Windows Machine? You'll need to check you've got a modern version of Pandoc (e.g. 2.7.3) as RST notes were not supported in early versions such as 1.19.

### ReStructuredText 

#### Input

```rst
.. Note:: This document is an informal introduction to
   reStructuredText.  The `What Next?`_ section below has links to
   further resources, including a formal reference.
```

#### DITA  Output
```xml
    <note type="note">
      <p>This document is an informal introduction to
reStructuredText. The
        <xref format="dita" href="#what-next">What Next?</xref>section below has links to
further resources, including a formal reference.</p>
    </note>
```

**Example:** [here](https://github.com/jason-fox/fox.jason.passthrough.pandoc/tree/master/test/input-restructured-text)

### Markdown

#### Input

```markdown
---

## Note {.note}

Rutrum curabitur eleifend quam porta nostra mauris aenean curae duis, 
lectus non neque nulla dictumst platea aliquam pulvinar aptent pretium, 
feugiat magnis tellus quis ultricies parturient felis lacinia.

---
```

#### DITA Output
```xml
    <note type="note">
      <p>Rutrum curabitur eleifend quam porta nostra mauris aenean curae duis, 
lectus non neque nulla dictumst platea aliquam pulvinar aptent pretium, 
feugiat magnis tellus quis ultricies parturient felis lacinia.</p>
    </note>
```

**Example:** [here](https://github.com/jason-fox/fox.jason.passthrough.pandoc/blob/master/test/topic-single-with-notes)

**Comment by lief-erickson** [comment]
I was already using Pandoc 2.7.3 so that was not an issue.

I updated to [acf58e8](https://github.com/jason-fox/fox.jason.passthrough/commit/acf58e86af4e0f40773f40d199256878a4010c86) in fox.jason.passthrough. I also updated to [5533b5c](https://github.com/jason-fox/fox.jason.passthrough.pandoc/commit/5533b5c829605030aa768d06607112e4d78268bd) in this repo.

I attempted to run my test and got this error.

> Error: Target "swagger.process.pre" does not exist in the project "DOST". It is used from target "passthrough.init".

I installed that plugin and got error that the "fox.jason.extend.css" plugin was also required.

After installing passthrough.swagger and extend.css, the `<note>` is being created as expected in my test file.

**Comment by jason-fox** [comment]
> I updated to [acf58e8](https://github.com/jason-fox/fox.jason.passthrough/commit/acf58e86af4e0f40773f40d199256878a4010c86) in fox.jason.passthrough. I also updated to [5533b5c](https://github.com/jason-fox/fox.jason.passthrough.pandoc/commit/5533b5c829605030aa768d06607112e4d78268bd) in this repo.

If you run `dita --install` after that, then you shouldn't need the other plugins. The issue here is using the `git` command rather than the `dita` command.

**Comment by jason-fox** [comment]
> After installing passthrough.swagger and extend.css, the `<note>` is being created as expected in my test file.

It appears `<note>` processing is now working on Mac, Linux and Windows.
